name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Chrome and ChromeDriver
      uses: actions/setup-chrome@v1  # Automatically installs Chrome and ChromeDriver
      with:
        chrome-version: latest  # Ensures the latest version of Chrome is installed

    - name: Configure Chrome environment variables
      run: |
        echo "CHROME_HEADLESS=true" >> $GITHUB_ENV  # Set Chrome to run in headless mode

    - name: Create reports directory
      run: mkdir -p $GITHUB_WORKSPACE/reports  # Ensure the reports directory exists

    - name: Run Maven Tests
      run: mvn test -Dextent.report.path=$GITHUB_WORKSPACE/reports/ExtentReport.html

    - name: Upload Extent Report
      uses: actions/upload-artifact@v3
      with:
        name: ExtentReport
        path: $GITHUB_WORKSPACE/reports/ExtentReport.html
