name: Run Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'
      email_subject:
        description: 'Subject of the email'
        required: true
        default: 'Run Automation Test'
      email_body:
        description: 'Body of the email'
        required: true
        default: 'Here is the test report.'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set environment variables for Chrome
      run: |
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV  # Set Chrome to run in headless mode
        
    - name: Run Maven Tests and Generate Report
      run: mvn clean test  # Running tests to generate reports

    - name: Read the HTML report and embed it in the email body
      id: embed-report
      run: |
        # Read the content of the extentReports.html into a variable using PowerShell
        $REPORT_BODY = Get-Content -Path "ExtentReports/extentReports.html" -Raw
        echo "REPORT_BODY<<EOF" >> $GITHUB_ENV
        echo "$REPORT_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: pwsh

    - name: Send Email with Embedded Report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        to: ramesharavindhkarthikeyan.qa@gmail.com
        from: ${{ secrets.EMAIL_FROM }}
        subject: ${{ github.event.inputs.email_subject }}
        body: |
          <html>
          <body>
            <p>${{ github.event.inputs.email_body }}</p>
            <hr>
            <h3>Test Report:</h3>
            <div>${{ env.REPORT_BODY }}</div>  <!-- Embedding raw HTML report content -->
          </body>
          </html>
        is_html: true  # Important to make sure it's treated as HTML
