name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'
      email_subject:
        description: 'Subject of the email'
        required: true
        default: 'Run Automation Test'
      email_body:
        description: 'Body of the email'
        required: true
        default: 'Here is the test report.'

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set environment variables for Chrome
      run: |
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV
        
    - name: Run Maven Tests and Generate Report
      run: mvn clean test
     
    - name: Comprehensive File Search
      run: |
        powershell -Command "Get-ChildItem -Path . -Recurse -Include *report*.html | Select-Object FullName"
        
    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        to: ramesharavindhkarthikeyan.qa@navadhiti.com
        cc: ${{ secrets.CLIENT_EMAIL }}
        from: ${{ secrets.EMAIL_FROM }}
        subject: ${{ github.event.inputs.email_subject }}
        body: |
          Dear Client,

          We hope this message finds you well.

          As requested, the automation tests have been successfully executed. The detailed test report is attached for your review. These tests were generated and configured as per your specifications by Navadhiti Business Consultancy Solutions.

          If you have any questions or require assistance, feel free to reach out to us.

          Best regards,  
          Ramesh Aravindh
          Quality Assurance Engineer
          
        attachments: |
          target\**\*report*.html
          **\*report*.html
