name: Run Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'
      email_subject:
        description: 'Subject of the email'
        required: true
        default: 'Run Automation Test'
      email_body:
        description: 'Body of the email'
        required: true
        default: 'Here is the test report.'
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set environment variables for Chrome
      run: |
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV  # Set Chrome to run in headless mode
    - name: Run Maven Tests and Generate Report
      run: mvn clean test  # Running tests to generate reports
    - name: Debug:List Files in Workspace
      run: |
        ls -R
    - name: Verify Report File Exists
      run: |
        if [ ! -f extentReports.html ]; then
          echo "Report file not found!";
          exit 1;
        fi
    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        to: ramesharavindhkarthikeyan.qa@gmail.com
        from: ${{ secrets.EMAIL_FROM }}
        subject: ${{ github.event.inputs.email_subject }}
        body: ${{ github.event.inputs.email_body }}
        attachments: extentReports.html
