name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'
      email_subject:
        description: 'Subject of the email'
        required: true
        default: 'Run Automation Test'
      email_body:
        description: 'Body of the email'
        required: true
        default: 'Here is the test report.'

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set environment variables for Chrome
      run: |
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV
        
    - name: Run Maven Tests and Generate Report
      run: mvn clean test
     
    - name: Comprehensive File Search
      run: |
        # Detailed file discovery
        powershell -Command "Get-ChildItem -Path . -Recurse -Include *report*.html | Select-Object FullName"
        
    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # Use GitHub's actor to send the email only to the person who triggered the workflow
        to: ${{ secrets['CLIENT_EMAIL_' + github.actor] }}  # This will dynamically select the email based on the actor's username
        from: ${{ secrets.EMAIL_FROM }}
        subject: ${{ github.event.inputs.email_subject }}
        body: |
          Dear ${{ secrets.CLIENT_NAME }},  # Use the CLIENT_NAME secret for dynamic greeting

          We hope this message finds you well.

          As requested, the automation tests have been successfully executed. Please find attached the detailed test report, which has been generated and configured as per your specifications by Navadhiti Business Consultancy Solutions. We are pleased to inform you that the tests were completed as expected.

          If you require any further information or assistance, please feel free to reach out to us. We are committed to providing continuous support and ensuring that all your requirements are met with the highest standard.

          Thank you for trusting Navadhiti Business Consultancy Solutions to handle your automation needs.

          Best regards,  
          ${{ secrets.EMAIL_USERNAME }}  
          Quality Assurance Engineer  
          Navadhiti Business Consultancy Solutions  
          ${{ secrets.CONTACT_INFORMATION }}

        attachments: |
          target\**\*report*.html
