name: Run Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set environment variables for Chrome
      run: echo CHROME_HEADLESS=false >> $env:GITHUB_ENV
    
    - name: Run Maven Tests with Extent Reports
      run: mvn clean test -Dmaven.test.failure.ignore=true
    
    - name: Upload Extent Report
      uses: actions/upload-artifact@v3
      with:
        name: ExtentReport
        path: target/ExtentReports/extentReports.html
