name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'feature'

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Run Maven Tests and Generate Extent Report
    - name: Run Maven Tests
      run: |
        mvn clean test -Dextent.report.path=target/ExtentReports/extentReports.html
      env:
        CHROME_HEADLESS: false

    # Step 4: Verify Report Generation
    - name: Verify Generated Files
      run: |
        echo "Checking the Extent Report..."
        dir target/ExtentReports /s

    # Step 5: Upload Extent Report
    - name: Upload Extent Report
      uses: actions/upload-artifact@v3
      with:
        name: ExtentReport
        path: target/ExtentReports/extentReports.html
